name: Publish to LuaRocks

on: 
  release:
    types: [ published ]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0

      - uses: leafo/gh-actions-lua@d84e7d61946edb679210088bc1378c099fde51fe # tag=v9.1.0

      - uses: leafo/gh-actions-luarocks@e65774a6386cb4f24e293dca7fc4ff89165b64c5 # tag=v4.3.0

      - run: luarocks install dkjson

      - run: luarocks upload --api-key ${{ secrets.API_KEY }}  rockspecs/du-bundler-${GITHUB_REF##*/v}-1.rockspec
