name: Tests

on: [ push, pull_request ]

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        luaVersion: [ "5.1", "5.2", "5.3", "5.4" ]

    steps:
      - uses: actions/checkout@master

      - uses: leafo/gh-actions-lua@v9
        with:
          luaVersion: ${{ matrix.luaVersion }}

      - uses: leafo/gh-actions-luarocks@v4

      - name: Setup
        run: |
          luarocks install --only-deps du-bundler-scm-0.rockspec
          luarocks install luaunit
          luarocks install luacov
          mkdir test/results

      - name: Test
        run: ./test/TestBundleTemplate.lua
