name: Test

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  luarocks:
    name: Test LuaRocks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0

      - uses: leafo/gh-actions-lua@d84e7d61946edb679210088bc1378c099fde51fe # v9.1.0

      - uses: leafo/gh-actions-luarocks@e65774a6386cb4f24e293dca7fc4ff89165b64c5 # v4.3.0

      - name: Setup
        run: |
          luarocks install --only-deps du-bundler-scm-0.rockspec

      - name: Verify LuaRocks config
        run: luarocks make

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
#        luaVersion: [ "5.3" ]
        luaVersion: [ "5.1", "5.2", "5.3", "5.4" ]

    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0

      - uses: leafo/gh-actions-lua@d84e7d61946edb679210088bc1378c099fde51fe # tag=v9.1.0
        with:
          luaVersion: ${{ matrix.luaVersion }}

      - uses: leafo/gh-actions-luarocks@e65774a6386cb4f24e293dca7fc4ff89165b64c5 # tag=v4.3.0

      - name: Setup
        run: |
          luarocks install --only-deps du-bundler-scm-0.rockspec
          luarocks install luaunit
          luarocks install luacov
          luarocks install luafilesystem
          mkdir test/results

      - name: Test
        run: lua -lluacov ./test/TestBundleTemplate.lua -o junit -n test/results/TestBundleTemplate.xml

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@46ab8d49369d898e381a607119161771bc65c2a6 # v2.2.0
        if: always()
        with:
          junit_files: "test/results/**/*.xml"

      - name: Upload to Codecov
        uses: codecov/codecov-action@d9f34f8cd5cb3b3eb79b3e4b5dae3a16df499a70 # tag=v3.1.1
        if: ${{ matrix.luaVersion == '5.3' }}
