name: Tests

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
#        luaVersion: [ "5.3" ]
        luaVersion: [ "5.1", "5.2", "5.3", "5.4" ]

    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0

      - uses: leafo/gh-actions-lua@d84e7d61946edb679210088bc1378c099fde51fe # tag=v9.1.0
        with:
          luaVersion: ${{ matrix.luaVersion }}

      - uses: leafo/gh-actions-luarocks@e65774a6386cb4f24e293dca7fc4ff89165b64c5 # tag=v4.3.0

      - name: Setup
        run: |
          luarocks install --only-deps du-bundler-scm-0.rockspec
          luarocks install luaunit
          luarocks install luacov
          luarocks install luafilesystem
          mkdir test/results

      - name: Test
        run: lua -lluacov ./test/TestBundleTemplate.lua -o junit -n test/results/TestBundleTemplate.xml

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@b9f6c61d965bcaa18acc02d6daf706373a448f02 # tag=v1.40
        if: always()
        with:
          files: "test/results/**/*.xml"

      - name: Upload to Codecov
        uses: codecov/codecov-action@d9f34f8cd5cb3b3eb79b3e4b5dae3a16df499a70 # tag=v3.1.1
        if: ${{ matrix.luaVersion == '5.3' }}
